blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/TrogonStack/TrogonEventStore-Client-Go/discussions/new?category=ideas
    about: Request a feature to add to the client
  - name: Ask a Question
    url: https://github.com/TrogonStack/TrogonEventStore-Client-Go/discussions/new?category=q-a
    about: Ask questions and discuss with other community members.
