ReplicationIp: 0.0.0.0
NodeIp: 0.0.0.0

Auth:
  Methods:
    - oauth
  OAuth:
    Issuer: http://localhost:18080/realms/trogon-eventstore
    MetadataAddress: http://keycloak:8080/realms/trogon-eventstore/.well-known/openid-configuration
    Audiences:
      - trogon-eventstore-client
    RoleClaimType: role
    RequireHttpsMetadata: false
